import type { Department, Activity } from '../types';

export const DHAMMA_PATTANA_ACTIVITIES: Activity[] = [
    'Received Request',
    'Schedule Dashboard',
    'Staff Status',
    'Room Dashboard',
    'Meditator Dashboard',
    'Store Dashboard',
    'Housekeeping Maintenance Dashboard',
    'Task Status',
    'Meditation Done',
    'Meditator Request',
    'DPVT Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const FOOD_COURT_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Food Menu Dashboard',
    'Store Dashboard',
    'Housekeeping Maintenance Dashboard',
    'Food-Court Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const SOUVENIR_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Souvenir Items Dashboard',
    'Store Dashboard',
    'Housekeeping Maintenance Dashboard',
    'Souvenir Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const DHAMMALAY_ACTIVITIES: Activity[] = [
    'Received Request',
    'Schedule Dashboard',
    'Staff Status',
    'Room Dashboard',
    'Guest/DS Dashboard',
    'Store Dashboard',
    'Housekeeping Maintenance Dashboard',
    'Task Status',
    'Meditation Done',
    'Dhammalay Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const LIBRARY_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Books Dashboard',
    'Store Dashboard',
    'Housekeeping Maintenance Dashboard',
    'Library Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const ACADEMIC_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Course Dashboard',
    'Store Dashboard',
    'Housekeeping Maintenance Dashboard',
    'Academic Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const PARIYATTI_ACTIVITIES: Activity[] = [
    'Received Request',
    'Schedule Dashboard',
    'Staff Status',
    'Room Dashboard',
    'Guest/DS Dashboard',
    'Store Dashboard',
    'Housekeeping Maintenance Dashboard',
    'Task Status',
    'Meditation Done',
    'Pariyatti Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const PUBLICATION_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Publication Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const ARCHIVE_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Archive Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const CONSERVATION_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Conservation Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const PRESERVATION_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Preservation Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const RECEPTION_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Reception Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const MUSEUM_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Schedule Dashboard',
    'Received Request',
    'Store Dashboard',
    'Museum Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const PR_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'PR Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const ELECTRICAL_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Electrical Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const WATER_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Water Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const CIVIL_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Civil Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const KITCHEN_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Food Menu Dashboard',
    'Store Dashboard',
    'Housekeeping Maintenance Dashboard',
    'Kitchen Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const HOUSEKEEPING_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Housekeeping Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const SECURITY_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Security Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const ACCOUNTS_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Received Bills',
    'Store Dashboard',
    'Accounts Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const IT_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'IT Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const PURCHASE_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Purchase Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const STORE_ACTIVITIES: Activity[] = [
    'Task Status',
    'Staff Status',
    'Meditation Done',
    'Received Request',
    'Store Dashboard',
    'Store Bills',
    'Purchase Order',
    'Feedback',
    'Survey',
    'Announcements',
    'CCTV',
    'Policies',
];

export const DEPARTMENT_ACTIVITIES: Partial<Record<Department, Activity[]>> = {
    'Dhamma-Pattana': DHAMMA_PATTANA_ACTIVITIES,
    'Food-Court': FOOD_COURT_ACTIVITIES,
    'Souvenir': SOUVENIR_ACTIVITIES,
    'Dhammalay': DHAMMALAY_ACTIVITIES,
    'Library': LIBRARY_ACTIVITIES,
    'Academic': ACADEMIC_ACTIVITIES,
    'Pariyatti': PARIYATTI_ACTIVITIES,
    'Publication': PUBLICATION_ACTIVITIES,
    'Archive': ARCHIVE_ACTIVITIES,
    'Conservation': CONSERVATION_ACTIVITIES,
    'Preservation': PRESERVATION_ACTIVITIES,
    'Reception': RECEPTION_ACTIVITIES,
    'Museum': MUSEUM_ACTIVITIES,
    'PR': PR_ACTIVITIES,
    'Electrical': ELECTRICAL_ACTIVITIES,
    'Water': WATER_ACTIVITIES,
    'Civil': CIVIL_ACTIVITIES,
    'Kitchen': KITCHEN_ACTIVITIES,
    'Housekeeping': HOUSEKEEPING_ACTIVITIES,
    'Security': SECURITY_ACTIVITIES,
    'Accounts': ACCOUNTS_ACTIVITIES,
    'IT': IT_ACTIVITIES,
    'Purchase': PURCHASE_ACTIVITIES,
    'Store': STORE_ACTIVITIES,
};
